### ISSUE TITLE
GUI en langue anglaise au lieu de française

### ISSUE THREAD

**Issue by Opware2000** [maelvls/homebrew-amc#28]
Suite à la mise à jour en 1.4.0_1 l'interface de AMC est passé en anglais au lieu du français comme précédemment.
Erreur constatée aussi bien avec la version stable que devel.

**Comment by maelvalais** [comment]
Bonjour,

Merci pour le retour ! Je jèterai un coup d’œil demain !

**Comment by maelvalais** [comment]
Bonsoir,

Je viens d'essayer ; je n'arrive pas à reproduire 😞

Voici mes essais avec la 1.4.0_1 :

    LC_ALL=en_us.UTF-8 auto-multiple-choice              -> apparaît en anglais
    LC_ALL=fr_FR.UTF-8 auto-multiple-choice              -> apparaît en français
    auto-multiple-choice                                 -> apparaît aussi en français

Pourriez-vous essayer les deux premières commandes et me dire si le résultat est le même que chez moi ? 🙂

Bonne soirée,

Maël

**Comment by Opware2000** [comment]
Bonsoir 
Merci pour vos tests.
```
LC_ALL=en_us.UTF-8 auto-multiple-choice              **-> apparaît en anglais**
LC_ALL=fr_FR.UTF-8 auto-multiple-choice              **-> apparaît en français**
auto-multiple-choice                                 **-> apparaît en ANGLAIS**
```
Peut-être est-ce que ça vient de ma version de Perl ?
This is perl 5, version 28, subversion 1 (v5.28.1) built for darwin-thread-multi-2level

Je vais juste éditer mon script de lancement pour rajouter LC_ALL=fr_FR.UTF-8  👍 
En tout cas merci pour votre sollicitude
