### ISSUE TITLE
Ancienne version d'AMC empêche l'installation

### ISSUE THREAD

**Issue by GizmoBen** [maelvls/homebrew-amc#30]
Bonjour,

Je ne sais pas pourquoi mais l'ancienne version d'AMC empêche la mise à jour.

> brew upgrade auto-multiple-choice
> Error: auto-multiple-choice 1.3.0.2199 already installed

Que puis-je faire ?

**Comment by maelvalais** [comment]
Coucou,

Bizarre, ça aurait dû marcher sans erreur 🙄

Serait-il possible d'essayer 

    brew uninstall auto-multiple-choice
    brew install auto-multiple-choice

Ça devrait régler le problème, mais pas sûr

**Comment by GizmoBen** [comment]
Ok je vais tenter ça, le problème c'est que maintenant j'ai généré un QCM et qu'en attendant d'avoir scanné l'examen, je n'ai pas envie de désinstaller/réinstaller car même si cela marche, j'ai peur des incompatibilités ;-).

**Comment by GizmoBen** [comment]
Bonjour Maël,

J’ai enfin transmis les cotes aux étudiants et organisé ma consultation de copies donc j’ai pu tester ta solution.

Tout d’abord il refusait de dés installer, j’ai du forcer avec la commande proposée, ensuite, impossible de réinstaller, il ne trouve pas AMC… J’ai essayé quelques solutions trouvées sur le web mais sans succès…

brew update
Already up-to-date.
brew install auto-multiple-choice
Error: No available formula with the name "auto-multiple-choice" 
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.



Du coup je suis bloqué sans possibilité de réinstaller (j’ai bien fait d’attendre hihi).

Merci de ton aide,

Benjamin

**Comment by GizmoBen** [comment]
Bonjour Maël,

J’ai enfin transmis les cotes aux étudiants et organisé ma consultation de copies donc j’ai pu tester ta solution.

Tout d’abord il refusait de dés installer, j’ai du forcer avec la commande proposée, ensuite, impossible de réinstaller, il ne trouvait pas AMC… J'ai du retaper la formule magique proposée ici ! Par contre est-ce normal qu'il me demande mon Username&Password Github ?

**Comment by maelvalais** [comment]
Aucune idée, bizarre : normalement, Homebrew configure git pour qu'il utilise l'URL en https, donc normalement aucun login/password ne devrait être demandé :

    > git -C /usr/local/Homebrew/Library/Taps/maelvalais/homebrew-amc/ config remote.origin.url
    https://github.com/maelvalais/homebrew-amc

Je crois cependant que parfois, lorsqu'on est sur un sous-réseau utilisant du NAT (genre grosse société qui va mutualiser l'usage des adresses IP publiques), on se retrouve avec des problèmes de [rate-limiting](https://developer.github.com/v3/#rate-limiting) ; et Github va, si la limite est atteinte, demander le username/password (ce qui permet de passer d'une limite de 60 requêtes par heure à 5000 requêtes par heure). Est-ce lié à cela ?

**Comment by maelvls** [comment]
Bonjour,

Le problème existe t-il toujours ?

**Comment by GizmoBen** [comment]
Bonjour,

Je ne saurais pas dire car après l’update vers Catalina, Homebrew avait l’air de souffrir donc j’ai dés installer Homebrew complètement et refait une clean install de AMC. Tout va bien maintenant !

Merci du suivi ;)

**Comment by maelvls** [comment]
Bonjour,
Je ferme ce ticket, vous pouvez réouvrir si le souci revient 🙂
