### ISSUE TITLE
Catalina bottle is missing

### ISSUE THREAD

**Issue by jaburgoyne** [maelvls/homebrew-amc#43]
There is no Homebrew bottle yet for Catalina (macOS 10.15), and on my machine, that is causing the Cairo handshake to fail:

> Cairo.c: loadable library and perl binaries are mismatched (got handshake key 0xc500080, needed 0xc400080)

Is it possible to get a Catalina bottle to build?

**Comment by maelvls** [comment]
Hi!

Sorry for the inconvenience, I'll take a look into that asap

**Comment by maelvls** [comment]
Added mojave and catalina in #44. Sorry for that 😁

**Comment by maelvls** [comment]
Closing issue. Feel free to reopen or open a new issue if anything goes wrong 🙂
