### ISSUE TITLE
Error while sending annotations using SMTP with SSL

### ISSUE THREAD

**Issue by serasset** [maelvls/homebrew-amc#46]
Hellp all,

I want to send annotated papers using SMTP with SSL and got the following error for each student :

ERROR [9] To use SSL please install IO::Socket::SSL with version>=2.007 at /usr/local/Cellar/perl/5.30.1/lib/perl5/5.30.1/Net/SMTP.pm line 68.

I installed amc using your brew cask long ago but updated recently : 

```
brew info auto-multiple-choice
maelvalais/amc/auto-multiple-choice: stable 1.4.0 (bottled)
printable tests for students with OCR marking
https://www.auto-multiple-choice.net
/usr/local/Cellar/auto-multiple-choice/1.4.0_8 (1,101 files, 28.5MB) *
  Poured from bottle on 2020-01-08 at 15:57:36
From: https://github.com/maelvalais/homebrew-amc/blob/master/auto-multiple-choice.rb
==> Dependencies
Build: librsvg ✔, make ✘
Required: adwaita-icon-theme ✔, cairo ✔, freetype ✔, gettext ✔, glib ✔, gobject-introspection ✔, gtk+3 ✔, imagemagick@6 ✔, libffi ✔, netpbm ✔, opencv ✔, amc-pango ✔, perl ✔, poppler ✔, qpdf ✔
==> Requirements
Required: x11 ✔
==> Caveats
...
```

Any idea ?

Thanks in advance and thanks a lot for this wonderful bottle !

Gilles,

**Comment by maelvls** [comment]
Hi! 👋 
Thanks, I appreciate!

I’ll take a look tomorrow morning. It might be that I didn’t know I had to add IO::Socket::SSL to the perl dependencies since I never used the sendmail backend

**Comment by serasset** [comment]
I finally managed to send the email using sendmail with msmtp command, rather than by using SMTP in the AMC GUI.

https://project.auto-multiple-choice.net/projects/auto-multiple-choice/wiki/Setup_AMC_to_send_email 

This worked like a charm. Maybe this could be rather a fix in the doc...

**Comment by maelvls** [comment]
Would you prefer having these doc changes in https://www.auto-multiple-choice.net/ ? Or here, in the hombrew-amc tap?

**Comment by maelvls** [comment]
Hi! As part of #57, `IO::Socket::SSL` is now installed and you should be able to send emails over TLS now!

Let me know if it still does not work.
