### ISSUE TITLE
pb lors de l'installation d'AMC : kpsewhich introuvable

### ISSUE THREAD

**Issue by oobouillot** [maelvls/homebrew-amc#47]
Bonjour,

Je souhaite installer AMC sur Catalina. Avec brew, j'utilise donc :

`brew install maelvls/amc/auto-multiple-choice`

Lorsque je lance AMC en Terminal, par `auto-multiple-choice`, le message suivant apparait :

"Je ne trouve pas la commande kpsewhich. Peut-être LaTeX n'est-il pas installé ?"

Ensuite, j'ai tenté de faire `sudo auto-multiple-choice latex-link remove`
J'obtiens alors un pudique : 
`ERROR: I don't find the command kpsewhich. Perhaps LaTeX is not installed?`

Evidement, mon ordi est tout neuf, mais j'avais installé LaTeX avant !

Si quelqu'un a une idée, je suis preneur !

**Comment by maelvls** [comment]
Bonjour et bienvenue,

Que donne `readlink -f $(which tex)`? Chez moi:

```sh
% readlink -f $(which tex)
/usr/local/texlive/2019basic/bin/x86_64-darwin/tex
```

**Comment by oobouillot** [comment]
Bonjour,

Cette commande ne me donne rien d'autre qu'une erreur... alors que j'ai copié/collé la ligne de commande ;-(

`readlink: illegal option -- f
usage: readlink [-n] [file ...]`

Par contre, je ne sais pas ce que j'ai tenté entre temps. Mais en relançant `auto-multiple-choice` en terminal, le message de mise en garde n'était plus le même. Il disait de faire `sudo auto-multiple-choice latex-link remove`, ce que j'ai fait, puis `sudo auto-multiple-choice latex-link`.

J'obtiens alors bien :
`Calling mktexlsr to refresh LaTeX files list...
Creating link to AMC style file...
Calling mktexlsr to refresh LaTeX files list...
Saving information about this 'latex-link' run in /etc/AMC/latex-link...
Done, 'automultiplechoice.sty' is now reachable from latex.
`

Cela a donc l'air d'être bon. Reste plus qu'à tester avec un vrai projet !

Merci pour cette formule.
