### ISSUE TITLE
problem with texinputs var on osx

### ISSUE THREAD

**Issue by mbrebion** [maelvls/homebrew-amc#48]
Hi, 
I've just installed amc via homebrew, everything worked fine but when I try to launch the gui, i get this endless message : 
```
warning: kpathsea: variable `TEXINPUTS' references itself (eventually).
warning: kpathsea: variable `TEXINPUTS' references itself (eventually).
warning: kpathsea: variable `TEXINPUTS' references itself (eventually).
warning: kpathsea: variable `TEXINPUTS' references itself (eventually).
...
```

I'm not using this env variable as I prefer using the texmf directory to put my personal tex files. However, I don't know how to fix this problem and any help would be appreciated !

**Comment by maelvls** [comment]
Hi!

No idea what is causing that 😕 Does anyone else have had the issue on the official amc forums?

**Comment by maelvls** [comment]
Closing for now. Feel free to re-open if this is still an issue. 👍
