### ISSUE TITLE
Problem to access to preferences 

### ISSUE THREAD

**Issue by sylbui** [maelvls/homebrew-amc#62]
Hello,

I had to reinstall AMC on my mac pro (catalina) with the homebrew formula.
I have disabled the Mac tab display in the system preferences and after opening AMC with or without a project, I can't access the preferences. I had to change the detection parameters.

I get the following error message:
Use of uninitialized value $both in concatenation (.) or string at /usr/local/Cellar/auto-multiple-choice/1.4.0_8/lib/AMC/perl/AMC-gui.pl line 3626.

Could you please help me?

Thank you in advance.

**Comment by sylbui** [comment]
Sorry I find the solution. I re-installed gtk+3 with homebrew and it's working now.

**Comment by maelvls** [comment]
No problem. I will close this issue for now, feel free to re-open if the problem reappears.
