### ISSUE TITLE
Issue on Macbook pro with M1 chip - Linux Libertine is missing

### ISSUE THREAD

**Issue by brisfan** [maelvls/homebrew-amc#73]
Bonjour,

J'ai installé Auto-Multiple-Choice avec Homebrew. Puis j'ai installé MacTeX. 
J'ai lancé la commande "auto-multiple-choice latex-link"
Ensuite, j'ai téléchargé les polices Linux Libertines depuis : https://sourceforge.net/projects/linuxlibertine/
J'ai ajouté les polices Linux Libertines à "MacintoshHD/Library/Fonts"
Et là je peux lancer Auto-Multiple-Choice, mais quand je compile un fichier d'interrogation le logiciel me dit que les polices linux libertines ne sont pas installées.
Pouvez-vous m'aider?

Hello,

I installed Auto-Multiple-Choice with Homebrew. Then I installed MacTeX. 
I ran the command "auto-multiple-choice latex-link"
Then I downloaded the Linux Libertines fonts from: https://sourceforge.net/projects/linuxlibertine/
I added the Linux Libertines fonts to "MacintoshHD/Library/Fonts".
And there I can run Auto-Multiple-Choice, but when I compile a question file the software tells me that the linux libertines fonts are not installed.
Can you help me?

<img width="1436" alt="AMC" src="https://user-images.githubusercontent.com/95613667/144816095-7140c932-e88f-4785-aec7-d13a008a7202.png">

<img width="698" alt="Capture d’écran 2021-12-06 à 09 36 11" src="https://user-images.githubusercontent.com/95613667/144815969-76d0c256-2e5b-431d-94a3-16425c03770c.png">

**Comment by maelvls** [comment]
Hi,

I now remember hitting this Libertine issue, I documented a solution in the section [Troubleshooting](https://github.com/maelvls/homebrew-amc/blob/8c4864d17a53ed4d056526b4b19ac0da1442bcdf/README.md#troubleshooting) in the README:


**The font _Linux Libertine_ is not found!** Install Libertine using brew:

      brew cask install  homebrew/cask-fonts/font-linux-libertine

  Note that you must **drop the ending 'O'** in your AMC-TXT and tex files.
  The command to use in tex files is:

      \setmainfont{Linux Libertine}

  and in amc-tex files:

      Font: Linux Libertine

Let me know if that helps.

**Comment by brisfan** [comment]
Unfortunately I still get an error message :
<img width="682" alt="Capture d’écran 2021-12-06 à 10 40 49" src="https://user-images.githubusercontent.com/95613667/144823665-d6c87176-b953-406a-90fa-dcdc78ed63c7.png">

**Comment by maelvls** [comment]
My apologies, I gave you the old command ("brew cask install" was replace by "brew install" in December 2020). The command would be:

```
brew install homebrew/cask-fonts/font-linux-libertine
```

**Comment by brisfan** [comment]
It works! Thanks a lot!

However, I don't quite understand this 'O' thing that you have to drop. There is no 'O' at the end of my AMC-txt files.
Is this only for the command to change the font?

**Comment by maelvls** [comment]
The 'O' to drop is if you have a line in your AMC-txt file such as:

```
Font: Linux Libertine O
```

It also seems like Linux Libertine is only used for annotating.

I now remember that I change the default fonts from `Linux Libertine O` to `Linux Libertine` so that AMC can annotate. This is done when the formula is installed: 

https://github.com/maelvls/homebrew-amc/blob/e2f0706f34191033781c6bbdd43407688112d131/auto-multiple-choice.rb#L461-L463

**Comment by brisfan** [comment]
Ok thanks for all! :-)
