### ISSUE TITLE
meson issue ?

### ISSUE THREAD

**Issue by sebmavro** [maelvls/homebrew-amc#75]
Hello,

brew install fails with the following output : ../giscanner/meson.build:58:0: ERROR: File doctemplates does not exist.

System : Mac M1 Pro / Monterey 12.2.1

Thanks for the formula and all the work you have done on it :)

Please find log on the file attached.

[Tapping maelvls:amc.txt](https://github.com/maelvls/homebrew-amc/files/8193295/Tapping.maelvls.amc.txt)

**Comment by eli-schwartz** [comment]
This is upstream ticket https://gitlab.gnome.org/GNOME/gobject-introspection/-/issues/414 and fixed via https://gitlab.gnome.org/GNOME/gobject-introspection/-/commit/effb1e09dee263cdac4ec593e8caf316e6f01fe2

**Comment by sebmavro** [comment]
Hello,
Thank you for your reply. I don't know how to apply this correction. Could you provide me with a link that explains how to do this, please?

**Comment by sebmavro** [comment]
Formulae update ! Everything goes fine now. Many thanks.
