### ISSUE TITLE
Installation problem of AMC on Ventura 13.4.1 (c)

### ISSUE THREAD

**Issue by Shouman12** [maelvls/homebrew-amc#86]
Bonjour 
J'ai essayé d'installer AMC en utilisant la commande "brew install maelvls/amc/auto-multiple-choice". 
Quand j'ai écrit "auto-multiple-choice" dans le terminal, j'ai reçois ce message d'erreur : 
`shouman$ auto-multiple-choice
Typelib file for namespace 'GdkPixbuf', version '2.0' not found at /opt/local/lib/perl5/vendor_perl/5.34/darwin-thread-multi-2level/Glib/Object/Introspection.pm line 108.
BEGIN failed--compilation aborted at /opt/local/lib/AMC/perl/AMC-gui.pl line 26.
`
Pourriez-vous m'aider, s'il vous plaît 

Hello,
I tried to install AMC using the command "brew install maelvls/amc/auto-multiple-choice." 
When I typed "auto-multiple-choice" in the terminal, I received this error message
`shouman$ auto-multiple-choice
Typelib file for namespace 'GdkPixbuf', version '2.0' not found at /opt/local/lib/perl5/vendor_perl/5.34/darwin-thread-multi-2level/Glib/Object/Introspection.pm line 108.
BEGIN failed--compilation aborted at /opt/local/lib/AMC/perl/AMC-gui.pl line 26.
`
Could you please help me?"

**Comment by loikun** [comment]
I solved it with on mac M2 : 
                                                                                                                                               
```
$ brew install glib      
Warning: glib 2.80.0_2 is already installed, it's just not linked.
To link this version, run:
  brew link glib
$  brew link glib                                                                                                                                                       
Linking /opt/homebrew/Cellar/glib/2.80.0_2... 181 symlinks created.
```
